#!/bin/bash
echo "========== SEGMENTATION VERIFICATION =========="
echo ""
echo "Sample Piece_01 Breakline_0:"
head -7 /data/gpfs/projects/punim2657/sfs_preprocessing/NURBS_Dataset_20251103/SfS_pp/Breaklines/Pot_A_Piece_01_Breakline_0.pcd | grep "^#"
echo ""
echo "New Piece_01 Breakline_0:"
head -7 Dataset/Breaklines/Pot_A/Pot_A_Piece_01_Breakline_0.pcd | grep "^#"
echo ""
echo "Sample Piece_07 Breakline_0 (lowest sample count 30pts):"
head -7 /data/gpfs/projects/punim2657/sfs_preprocessing/NURBS_Dataset_20251103/SfS_pp/Breaklines/Pot_A_Piece_07_Breakline_0.pcd | grep "^#"
echo ""
echo "New Piece_07 Breakline_0 (lowest new count 43pts):"
head -7 Dataset/Breaklines/Pot_A/Pot_A_Piece_07_Breakline_0.pcd | grep "^#"
