function [C0, C1] = read_surfaces_nurbs(pot_id, frag_id, extended)
% Read NURBS-generated surface files for axis extraction
% Compatible with NURBS preprocessing output format

if nargin < 3, extended = false; end

% Base directory for NURBS preprocessing output  
base_dir = ''; % MATLAB runs from root directory, no relative path needed

% NURBS surface files generated by MeshPreprocessingHeadless
surface_0_file = sprintf('%sDataset/SfS_pp/Surfaces/Pot_%s_Piece_%02d_Surface_0.xyz', ...
                        base_dir, pot_id, frag_id);
surface_1_file = sprintf('%sDataset/SfS_pp/Surfaces/Pot_%s_Piece_%02d_Surface_1.xyz', ...
                        base_dir, pot_id, frag_id);

fprintf('Reading NURBS surfaces:\n');
fprintf('  Surface 0: %s\n', surface_0_file);
fprintf('  Surface 1: %s\n', surface_1_file);

% Check if NURBS surface files exist
if ~exist(surface_0_file, 'file')
    error('NURBS Surface 0 file not found: %s', surface_0_file);
end

try
    % Load NURBS surface data (format: X Y Z Nx Ny Nz)
    surface_0_data = readmatrix(surface_0_file, 'FileType', 'text');
    fprintf('  ✅ Loaded Surface 0: %d points\n', size(surface_0_data, 1));
    
    % Transpose to match PotSAC expected format [6 x N]
    C0 = surface_0_data'; % [X Y Z Nx Ny Nz; ...]' -> [6 x N]
    
    % Ensure we have 6 rows (coordinates + normals)
    if size(C0, 1) ~= 6
        error('Invalid NURBS surface format. Expected 6 columns (X Y Z Nx Ny Nz), got %d', size(C0, 1));
    end
    
catch read_error
    error('Failed to read NURBS Surface 0: %s', read_error.message);
end

% Load second surface if requested
if nargout > 1
    if ~exist(surface_1_file, 'file')
        error('NURBS Surface 1 file not found: %s', surface_1_file);
    end
    
    try
        surface_1_data = readmatrix(surface_1_file, 'FileType', 'text');
        fprintf('  ✅ Loaded Surface 1: %d points\n', size(surface_1_data, 1));
        
        % Transpose to match PotSAC expected format [6 x N]
        C1 = surface_1_data';
        
        % Ensure we have 6 rows (coordinates + normals)
        if size(C1, 1) ~= 6
            error('Invalid NURBS surface format. Expected 6 columns (X Y Z Nx Ny Nz), got %d', size(C1, 1));
        end
        
    catch read_error
        error('Failed to read NURBS Surface 1: %s', read_error.message);
    end
end

fprintf('  🎯 NURBS surfaces ready for PotSAC axis extraction\n');

end